services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ADMIN_EMAIL: admin@the-hunt.dev
      ADMIN_PASSWORD: admin
      CORS_TRUST_ORIGINS: "http://localhost:9000,http://localhost:9900"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      maildev:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./docker-compose.yaml
        - action: sync+restart
          path: ./internal
          target: /app/internal
        - action: sync+restart
          path: ./cmd
          target: /app/cmd
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum

  prod-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_ENV: production
    ports:
      - "4010:4000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      maildev:
        condition: service_started
    profiles:
      - prod-test

  cors-simple:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ["go", "run", "./simple"]
    volumes:
      - ./examples/cors/simple/:/app/simple/
    ports:
      - "9000:9000"
    depends_on:
      api:
        condition: service_started
    profiles:
      - examples

  cors-preflight:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ["go", "run", "./preflight"]
    volumes:
      - ./examples/cors/preflight/:/app/preflight/
    ports:
      - "9900:9000"
    depends_on:
      api:
        condition: service_started
    profiles:
      - examples

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: compose-db-name
      POSTGRES_USER: compose-db-user
      POSTGRES_PASSWORD: compose-db-pswd
    ports:
      - "5432:5432"
    volumes:
      - ./etc/postgres/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compose-db-user -d compose-db-name"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: gomicro/goose
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://compose-db-user:compose-db-pswd@db:5432/compose-db-name?sslmode=disable"
      GOOSE_MIGRATION_DIR: /migrations
    command: ["goose", "up"]

  maildev:
    image: djfarrelly/maildev
    environment:
      MAILDEV_INCOMING_USER: compose-mail-user
      MAILDEV_INCOMING_PASS: compose-mail-pswd
      MAILDEV_OUTGOING_USER: compose-mail-user
      MAILDEV_OUTGOING_PASS: compose-mail-pswd
    restart: always
    ports:
      - 1080:80
      - 1025:25

volumes:
  pg_data:
