#!/usr/bin/bash

# Migrates the database down by 1 step.
# Specify a specific migration to migrate to with the only arg.

set -euxo pipefail

if [[ $# -eq 0 ]]; then
  docker compose run --rm migrate goose down
else
  docker compose run --rm migrate goose down-to $1
fi

