#!/usr/bin/bash

# Clears out the compose-db-name database

set -euxo pipefail

docker compose run \
    --rm \
    --volume=$(pwd)/etc/nuke.sql:/nuke.sql:ro \
    db \
    psql 'postgres://compose-db-user:compose-db-pswd@db:5432/compose-db-name?sslmode=disable' \
    -f /nuke.sql
